name: Version Bump

on:
  push:
    # branches:
    #   - main
    paths:
      - VERSION

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: "$(cat VERSION)"
